### PR TITLE
Issue #54: Wait condition times out when creating in an existing VPC …

### PR DESCRIPTION
**Pull request by joncourt**
…private subnet (2nd try - this time without the eol changes)

- modified all http://instance-data/... to http://169.254.169.254/... inline with AWS recommendation here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

### CODE REVIEW

**Comment by cyan-confluent** [comment]
Ok, I will give this a quick run tomorrow morning to test a couple of other configurations. Will thumbs up afterwards.

@dbtucker I like the ip change. Do you approve?

**Comment by joncourt** [comment]
cool. thanks @cyan-confluent.

regards,
jon

**Comment by cyan-confluent** [comment]
I've gone and tested this for Amazon AMI, Centos 7, Ubuntu 16.04, non-VPC and VPC configurations, it looks good.

@joncourt In the future, commit to the develop branch instead of the master, so Amazon's CI system can pick up the the changes and do a sanity test.

Since I've verified the logic manually this time, I think it's good to go straight to master.

LGTM 👍

**Comment by cyan-confluent** [comment]
@santiagocardenas Please merge. Thanks!

**Comment by santiagocardenas** [comment]
@joncourt Please confirm that this contribution is under the Apache 2.0 license terms.

Thanks,
Santiago

**Comment by cyan-confluent** [comment]
Resolves #56 #45

**Comment by joncourt** [comment]
@cyan-confluent noted.

@santiagocardenas yes Apache 2.0 license terms.

Regards
Jon

**Pull request merged**
